root: true
extends:
  - remcohaszing
  - remcohaszing/typechecking
rules:
  no-duplicate-imports: off

  import/extensions: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off

  jsdoc/require-jsdoc: off

  node/no-extraneous-import: off
  node/no-unsupported-features/es-builtins: off
  node/no-unsupported-features/es-syntax: off
  node/no-unsupported-features/node-builtins: off
overrides:
  - files:
      - examples/esbuild-demo/build.js
    rules:
      no-console: off
